# Generated by Django 5.0.1 on 2026-01-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0002_historicaltenant'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_super_admin', False), ('tenant__isnull', False)), fields=('tenant', 'email'), name='unique_email_per_tenant_user'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_super_admin', True), ('tenant__isnull', True)), fields=('email',), name='unique_email_super_admin'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_super_admin', False), ('phone_number__gt', ''), ('tenant__isnull', False)), fields=('tenant', 'phone_number'), name='unique_phone_per_tenant_user'),
        ),
    ]
