# Generated by Django 5.0.1 on 2026-01-19 08:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_unique_email_per_tenant_user_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="unique_email_per_tenant_user",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="unique_email_super_admin",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="unique_phone_per_tenant_user",
        ),
    ]
