# Generated by Django 5.0.1 on 2026-01-21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('accounts', '0003_remove_user_unique_email_per_tenant_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVehicleTypeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(db_index=True, max_length=20)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_vehicle_type_assignment_created_set', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_vehicle_type_assignments', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_vehicle_type_assignment_updated_set', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_type_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='uservehicletypeassignment',
            index=models.Index(fields=['tenant', 'user', 'vehicle_type'], name='accounts_us_tenant__user__vehicle_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='uservehicletypeassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'user', 'vehicle_type'), name='unique_user_vehicle_type_assignment'),
        ),
    ]
