# Generated by Django 5.0.1 on 2026-01-21 14:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_user_vehicle_type_assignment"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="uservehicletypeassignment",
            new_name="accounts_us_tenant__1fe9f3_idx",
            old_name="accounts_us_tenant__user__vehicle_type_idx",
        ),
    ]
