# Generated by Django 5.0.1 on 2026-01-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0005_rename_accounts_us_tenant__user__vehicle_type_idx_accounts_us_tenant__1fe9f3_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="must_change_password",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="If true, user must set a new password before accessing the dashboard",
            ),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="password_last_reset_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="If true, user must set a new password before accessing the dashboard",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="password_last_reset_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
