# Generated by Django 5.0.1 on 2026-01-03 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('customer', 'Customer'), ('vehicle', 'Vehicle'), ('policy', 'Policy')], db_index=True, max_length=20)),
                ('name', models.CharField(help_text='Human-readable label', max_length=255)),
                ('key', models.SlugField(help_text='Machine key, unique per tenant+entity', max_length=100)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean'), ('dropdown', 'Dropdown')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('options', models.JSONField(blank=True, default=list, help_text='Allowed options for dropdown')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_definitions', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', 'entity_type', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('text_value', models.TextField(blank=True)),
                ('number_value', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('date_value', models.DateField(blank=True, null=True)),
                ('bool_value', models.BooleanField(blank=True, null=True)),
                ('option_value', models.CharField(blank=True, max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='dynamic_fields.fielddefinition')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_values', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', 'definition_id', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='fielddefinition',
            index=models.Index(fields=['tenant', 'entity_type', 'is_active'], name='dynamic_fie_tenant__491d1c_idx'),
        ),
        migrations.AddIndex(
            model_name='fielddefinition',
            index=models.Index(fields=['tenant', 'entity_type', 'key'], name='dynamic_fie_tenant__448b50_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fielddefinition',
            unique_together={('tenant', 'entity_type', 'key')},
        ),
        migrations.AddIndex(
            model_name='fieldvalue',
            index=models.Index(fields=['tenant', 'definition'], name='dynamic_fie_tenant__8c203d_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldvalue',
            index=models.Index(fields=['tenant', 'content_type', 'object_id'], name='dynamic_fie_tenant__3fed0c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fieldvalue',
            unique_together={('tenant', 'definition', 'content_type', 'object_id')},
        ),
    ]
