# Generated by Django 5.0.1 on 2026-01-08 07:41

from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def dedupe_before_constraints(apps, schema_editor):
    Customer = apps.get_model('core', 'Customer')
    Policy = apps.get_model('core', 'Policy')
    now = timezone.now()

    # Deduplicate company customers by (tenant, registration_number)
    company_dups = (
        Customer.objects
        .filter(customer_type='company', registration_number__gt='', deleted_at__isnull=True)
        .values('tenant_id', 'registration_number')
        .annotate(c=models.Count('id'))
        .filter(c__gt=1)
    )
    for g in company_dups:
        qs = (
            Customer.objects
            .filter(
                customer_type='company',
                tenant_id=g['tenant_id'],
                registration_number=g['registration_number'],
                deleted_at__isnull=True,
            )
            .order_by('-updated_at', '-id')
        )
        keep = qs.first()
        if keep:
            qs.exclude(pk=keep.pk).update(deleted_at=now)

    # Deduplicate individual customers by (tenant, id_number)
    individual_dups = (
        Customer.objects
        .filter(customer_type='individual', id_number__gt='', deleted_at__isnull=True)
        .values('tenant_id', 'id_number')
        .annotate(c=models.Count('id'))
        .filter(c__gt=1)
    )
    for g in individual_dups:
        qs = (
            Customer.objects
            .filter(
                customer_type='individual',
                tenant_id=g['tenant_id'],
                id_number=g['id_number'],
                deleted_at__isnull=True,
            )
            .order_by('-updated_at', '-id')
        )
        keep = qs.first()
        if keep:
            qs.exclude(pk=keep.pk).update(deleted_at=now)

    # Deduplicate policy numbers by (tenant, policy_number)
    policy_dups = (
        Policy.objects
        .filter(policy_number__gt='', deleted_at__isnull=True)
        .values('tenant_id', 'policy_number')
        .annotate(c=models.Count('id'))
        .filter(c__gt=1)
    )
    for g in policy_dups:
        qs = (
            Policy.objects
            .filter(
                tenant_id=g['tenant_id'],
                policy_number=g['policy_number'],
                deleted_at__isnull=True,
            )
            .order_by('-updated_at', '-id')
        )
        keep = qs.first()
        if keep:
            qs.exclude(pk=keep.pk).update(deleted_at=now)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('tenants', '0002_historicaltenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='policy_number',
            field=models.CharField(db_index=True, help_text='Unique policy number', max_length=100),
        ),
        migrations.RunPython(dedupe_before_constraints, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('customer_type', 'individual'), models.Q(('id_number', ''), _negated=True)), fields=('tenant', 'id_number'), name='unique_individual_id_number_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('customer_type', 'company'), models.Q(('registration_number', ''), _negated=True)), fields=('tenant', 'registration_number'), name='unique_company_registration_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'policy_number'), name='unique_policy_number_per_tenant'),
        ),
    ]
