# Generated by Django 5.0.1 on 2026-01-19 08:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_permittype_conflicts"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="latrarecord",
            new_name="core_latrar_tenant__c27395_idx",
            old_name="core_latra_ten_veh_stat_idx",
        ),
        migrations.RenameIndex(
            model_name="latrarecord",
            new_name="core_latrar_tenant__bc7018_idx",
            old_name="core_latra_ten_latra_idx",
        ),
        migrations.RenameIndex(
            model_name="latrarecord",
            new_name="core_latrar_tenant__2cecf6_idx",
            old_name="core_latra_ten_start_idx",
        ),
        migrations.RenameIndex(
            model_name="latrarecord",
            new_name="core_latrar_tenant__a8e515_idx",
            old_name="core_latra_ten_end_idx",
        ),
        migrations.RenameIndex(
            model_name="permittype",
            new_name="core_permit_tenant__e3a76c_idx",
            old_name="core_ptype_ten_name_idx",
        ),
        migrations.RenameIndex(
            model_name="supportrequest",
            new_name="core_suppor_tenant__090347_idx",
            old_name="core_suppor_tenant__status_idx",
        ),
        migrations.RenameIndex(
            model_name="supportrequest",
            new_name="core_suppor_tenant__368748_idx",
            old_name="core_suppor_tenant__created_idx",
        ),
        migrations.RenameIndex(
            model_name="vehiclepermit",
            new_name="core_vehicl_tenant__0b2ea1_idx",
            old_name="core_vehperm_ten_veh_stat_idx",
        ),
        migrations.RenameIndex(
            model_name="vehiclepermit",
            new_name="core_vehicl_tenant__a8920f_idx",
            old_name="core_vehperm_ten_permit_idx",
        ),
        migrations.RenameIndex(
            model_name="vehiclepermit",
            new_name="core_vehicl_tenant__da57c6_idx",
            old_name="core_vehperm_ten_start_idx",
        ),
        migrations.RenameIndex(
            model_name="vehiclepermit",
            new_name="core_vehicl_tenant__55e319_idx",
            old_name="core_vehperm_ten_end_idx",
        ),
    ]
