# Generated by Django 5.0.1 on 2026-01-20 08:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_tenant_onboarding_state"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="tenantonboardingstate",
            new_name="core_tenant_tenant__1409d2_idx",
            old_name="core_tenanton_tenant__status_idx",
        ),
    ]
