# Generated by Django 5.0.1 on 2026-01-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0008_rename_core_tenanton_tenant__status_idx_core_tenant_tenant__1409d2_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="permittype",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
