# Generated by Django 5.0.1 on 2026-01-30 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_unified_lifecycle_management"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpolicy",
            name="cancellation_note",
            field=models.TextField(
                blank=True, help_text="Additional cancellation details"
            ),
        ),
        migrations.AddField(
            model_name="historicalpolicy",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="User who cancelled the policy",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="historicalpolicy",
            name="cancellation_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("customer_request", "Customer Request"),
                    ("non_payment", "Non-Payment"),
                    ("vehicle_sold", "Vehicle Sold"),
                    ("duplicate", "Duplicate Entry"),
                    ("data_error", "Data Error"),
                    ("other", "Other"),
                ],
                help_text="Reason for cancellation",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="latrarecord",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who cancelled the record",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cancelled_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="vehiclepermit",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who cancelled the record",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cancelled_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
