# Generated by Django 5.0.1 on 2026-02-06 07:53

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_unified_lifecycle_management"),
        ("tenants", "0002_historicaltenant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "base_manager_name": "all_objects",
                "ordering": ["-created_at"],
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
            },
        ),
        migrations.AlterModelManagers(
            name="customer",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="VehicleAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when record was soft-deleted",
                        null=True,
                    ),
                ),
                ("start_date", models.DateField(help_text="Assignment start date")),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Assignment end date (null for ongoing)",
                        null=True,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, help_text="Reason for assignment", max_length=255
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        help_text="Assigned driver",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicle_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Insurance company this record belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        help_text="Assigned vehicle",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="core.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle Assignment",
                "verbose_name_plural": "Vehicle Assignments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "vehicle", "start_date"],
                        name="core_vehicl_tenant__67ca1c_idx",
                    ),
                    models.Index(
                        fields=["tenant", "driver", "start_date"],
                        name="core_vehicl_tenant__c50bfa_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="vehicleassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True), ("end_date__isnull", True)
                ),
                fields=("tenant", "vehicle"),
                name="unique_active_vehicle_assignment",
            ),
        ),
    ]
