# Generated by Django 5.0.1 on 2026-04-10 15:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_alter_customer_options_alter_customer_managers_and_more"),
        ("core", "0012_vehicle_lifecycle_intelligence"),
    ]

    operations = [
        migrations.DeleteModel(
            name="VehicleAssignment",
        ),
    ]
