# Generated by Django 5.0.1 on 2025-12-29 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Official name of the insurance company', max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='URL-safe identifier for the tenant', max_length=255, unique=True)),
                ('domain', models.CharField(blank=True, help_text='Custom domain for this tenant (e.g., tenant.insurance.com)', max_length=255, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid domain name', regex='^[a-zA-Z0-9][a-zA-Z0-9-]{1,61}[a-zA-Z0-9]\\.[a-zA-Z]{2,}$')])),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this tenant can access the system')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Tenant-specific configuration (e.g., fleet_policy_enabled, expiry_reminder_days)')),
                ('contact_email', models.EmailField(help_text='Primary contact email for this tenant', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Primary contact phone number', max_length=20)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when tenant was soft-deleted', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug', 'is_active'], name='tenants_ten_slug_7c647c_idx'), models.Index(fields=['deleted_at'], name='tenants_ten_deleted_50d88b_idx')],
            },
        ),
    ]
