# Generated by Django 5.0.1 on 2026-01-05 08:27

import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTenant',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Official name of the insurance company', max_length=255)),
                ('slug', models.SlugField(help_text='URL-safe identifier for the tenant', max_length=255)),
                ('domain', models.CharField(blank=True, db_index=True, help_text='Custom domain for this tenant (e.g., tenant.insurance.com)', max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid domain name', regex='^[a-zA-Z0-9][a-zA-Z0-9-]{1,61}[a-zA-Z0-9]\\.[a-zA-Z]{2,}$')])),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this tenant can access the system')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Tenant-specific configuration (e.g., fleet_policy_enabled, expiry_reminder_days)')),
                ('contact_email', models.EmailField(help_text='Primary contact email for this tenant', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Primary contact phone number', max_length=20)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when tenant was soft-deleted', null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Tenant',
                'verbose_name_plural': 'historical Tenants',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
