# Generated by Django 5.0.1 on 2026-01-27 05:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0002_historicaltenant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="password_resets_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="password_resets_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="password_reset_events",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Password reset audit",
                "verbose_name_plural": "Password reset audits",
                "indexes": [
                    models.Index(
                        fields=["tenant", "created_at"],
                        name="audit_passw_tenant__4a82b9_idx",
                    ),
                    models.Index(
                        fields=["tenant", "target_user", "created_at"],
                        name="audit_passw_tenant__07797e_idx",
                    ),
                ],
            },
        ),
    ]
