from django.urls import path
from .views import (
    DashboardHomeView,
    OnboardingWelcomeView,
    OnboardingCompanyView,
    OnboardingVehicleBasicsView,
    OnboardingOwnerView,
    OnboardingDocumentsView,
    OnboardingSuccessView,
    OrganizationSettingsView,
    CustomerListView,
    CustomerExportView,
    CustomerCreateView,
    CustomerUpdateView,
    CustomerSoftDeleteView,
    VehicleListView,
    VehicleExportView,
    VehicleDetailView,
    VehicleCreateView,
    VehicleUpdateView,
    VehicleSoftDeleteView,
    PolicyListView,
    PolicyCreateView,
    PolicyDetailView,
    PolicyUpdateView,
    PolicyRenewView,
    PaymentCreateView,
    PaymentVerifyView,
    PaymentReviewView,
    PolicyReportView,
    RegistrationReportView,
    PolicyCancelView,
    SupportRequestListView,
    SupportRequestCreateView,
    LATRARecordCreateView,
    VehiclePermitCreateView,
    VehicleBulkImportView,
    StaffListView,
    StaffCreateView,
    StaffVehicleTypeUpdateView,
    PermitTypeListView,
    PermitTypeCreateView,
    PermitTypeUpdateView,
)
from apps.dynamic_fields.views import (
    FieldDefinitionListView,
    FieldDefinitionCreateView,
    FieldDefinitionUpdateView,
)

app_name = "dashboard"

urlpatterns = [
    path("", DashboardHomeView.as_view(), name="home"),
    path("onboarding/", OnboardingWelcomeView.as_view(), name="onboarding_welcome"),
    path("onboarding/company/", OnboardingCompanyView.as_view(), name="onboarding_company"),
    path("onboarding/vehicle/", OnboardingVehicleBasicsView.as_view(), name="onboarding_vehicle_basics"),
    path("onboarding/owner/", OnboardingOwnerView.as_view(), name="onboarding_owner"),
    path("onboarding/documents/", OnboardingDocumentsView.as_view(), name="onboarding_documents"),
    path("onboarding/success/", OnboardingSuccessView.as_view(), name="onboarding_success"),
    path("settings/organization/", OrganizationSettingsView.as_view(), name="organization_settings"),
    path("customers/", CustomerListView.as_view(), name="customers_list"),
    path("customers/export/", CustomerExportView.as_view(), name="customers_export"),
    path("customers/new/", CustomerCreateView.as_view(), name="customers_create"),
    path("customers/<int:pk>/edit/", CustomerUpdateView.as_view(), name="customers_update"),
    path("customers/<int:pk>/delete/", CustomerSoftDeleteView.as_view(), name="customers_delete"),
    path("vehicles/", VehicleListView.as_view(), name="vehicles_list"),
    path("vehicles/export/", VehicleExportView.as_view(), name="vehicles_export"),
    path("vehicles/<int:pk>/", VehicleDetailView.as_view(), name="vehicles_detail"),
    path("vehicles/new/", VehicleCreateView.as_view(), name="vehicles_create"),
    path("vehicles/import/", VehicleBulkImportView.as_view(), name="vehicles_import"),
    path("vehicles/<int:pk>/edit/", VehicleUpdateView.as_view(), name="vehicles_update"),
    path("vehicles/<int:pk>/delete/", VehicleSoftDeleteView.as_view(), name="vehicles_delete"),
    path("vehicles/<int:vehicle_pk>/latra/new/", LATRARecordCreateView.as_view(), name="vehicles_latra_create"),
    path("vehicles/<int:vehicle_pk>/permits/new/", VehiclePermitCreateView.as_view(), name="vehicles_permit_create"),
    path("policies/", PolicyListView.as_view(), name="policies_list"),
    path("policies/new/", PolicyCreateView.as_view(), name="policies_create"),
    path("policies/<int:pk>/", PolicyDetailView.as_view(), name="policies_detail"),
    path("policies/<int:pk>/edit/", PolicyUpdateView.as_view(), name="policies_update"),
    path("policies/<int:pk>/renew/", PolicyRenewView.as_view(), name="policies_renew"),
    path("policies/<int:pk>/cancel/", PolicyCancelView.as_view(), name="policies_cancel"),
    path("payments/new/", PaymentCreateView.as_view(), name="payments_create"),
    path("payments/<int:pk>/verify/", PaymentVerifyView.as_view(), name="payments_verify"),
    path("payments/<int:pk>/review/", PaymentReviewView.as_view(), name="payments_review"),
    path("policies/report/", PolicyReportView.as_view(), name="policies_report"),
    path("registrations/report/", RegistrationReportView.as_view(), name="registrations_report"),
    path("fields/", FieldDefinitionListView.as_view(), name="fields_list"),
    path("fields/new/", FieldDefinitionCreateView.as_view(), name="fields_create"),
    path("fields/<int:pk>/edit/", FieldDefinitionUpdateView.as_view(), name="fields_update"),
    path("support/", SupportRequestListView.as_view(), name="support_list"),
    path("support/new/", SupportRequestCreateView.as_view(), name="support_create"),
    path("staff/", StaffListView.as_view(), name="staff_list"),
    path("staff/new/", StaffCreateView.as_view(), name="staff_create"),
    path("staff/<int:user_pk>/vehicle-types/", StaffVehicleTypeUpdateView.as_view(), name="staff_vehicle_types"),
    path("permits/types/", PermitTypeListView.as_view(), name="permit_types_list"),
    path("permits/types/new/", PermitTypeCreateView.as_view(), name="permit_types_create"),
    path("permits/types/<int:pk>/edit/", PermitTypeUpdateView.as_view(), name="permit_types_update"),
]
