# Generated by Django 5.0.1 on 2026-02-02 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
        ("tenants", "0002_historicaltenant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantNotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when record was soft-deleted",
                        null=True,
                    ),
                ),
                ("policy_expiry_enabled", models.BooleanField(default=True)),
                ("payment_notifications_enabled", models.BooleanField(default=True)),
                ("compliance_alerts_enabled", models.BooleanField(default=True)),
                ("system_notifications_enabled", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "notifications_tenant_settings",
            },
        ),
        migrations.CreateModel(
            name="UserNotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when record was soft-deleted",
                        null=True,
                    ),
                ),
                ("policy_expiry_enabled", models.BooleanField(blank=True, null=True)),
                (
                    "payment_notifications_enabled",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "compliance_alerts_enabled",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "system_notifications_enabled",
                    models.BooleanField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "notifications_user_preferences",
            },
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("policy_expiry", "Policy Expiry"),
                    ("payment_due", "Payment Due"),
                    ("compliance_alert", "Compliance Alert"),
                    ("system_announcement", "System Announcement"),
                    ("user_activity", "User Activity"),
                    ("payment_verification_request", "Payment Verification Request"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["tenant", "vehicle_id", "-created_at"],
                name="notificatio_tenant__b6cb35_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["tenant", "policy_id", "type"],
                name="notificatio_tenant__e39679_idx",
            ),
        ),
        migrations.AddField(
            model_name="tenantnotificationsettings",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tenantnotificationsettings",
            name="tenant",
            field=models.ForeignKey(
                help_text="Insurance company this record belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="tenantnotificationsettings",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last updated this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usernotificationpreference",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usernotificationpreference",
            name="tenant",
            field=models.ForeignKey(
                help_text="Insurance company this record belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="usernotificationpreference",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last updated this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usernotificationpreference",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantnotificationsettings",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("tenant",),
                name="unique_active_notification_settings_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="usernotificationpreference",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("tenant", "user"),
                name="unique_active_notification_preferences_per_user",
            ),
        ),
    ]
